#if !canImport(ObjectiveC)
import XCTest

extension PackageGeneratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PackageGeneratorTests = [
        ("testGeneratedDescriptionHeader", testGeneratedDescriptionHeader),
        ("testGeneratedPackageWhenThereAreDependencies", testGeneratedPackageWhenThereAreDependencies),
        ("testGeneratedPackageWhenThereAreNoDependencies", testGeneratedPackageWhenThereAreNoDependencies),
    ]
}

extension PackageListMakerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PackageListMakerTests = [
        ("testParsesValidPackages", testParsesValidPackages),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PackageGeneratorTests.__allTests__PackageGeneratorTests),
        testCase(PackageListMakerTests.__allTests__PackageListMakerTests),
    ]
}
#endif
