#if !canImport(ObjectiveC)
    import XCTest

    extension BitBucketCloudTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__BitBucketCloudTests = [
            ("testCommentUserWithoutAccountId", testCommentUserWithoutAccountId),
            ("testCommitWithoutUser", testCommitWithoutUser),
            ("testParsesActivities", testParsesActivities),
            ("testParsesComments", testParsesComments),
            ("testParsesCommits", testParsesCommits),
            ("testParsesMetadata", testParsesMetadata),
            ("testParsesPR", testParsesPR),
        ]
    }

    extension BitBucketServerTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__BitBucketServerTests = [
            ("testItParsesBitbucketUserWithoutEmail", testItParsesBitbucketUserWithoutEmail),
            ("testItParsesTheBitBucketActivities", testItParsesTheBitBucketActivities),
            ("testItParsesTheBitBucketComments", testItParsesTheBitBucketComments),
            ("testItParsesTheBitBucketCommits", testItParsesTheBitBucketCommits),
            ("testItParsesTheBitBucketMetadata", testItParsesTheBitBucketMetadata),
            ("testItParsesTheBitBucketPullRequest", testItParsesTheBitBucketPullRequest),
        ]
    }

    extension DangerDSLTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__DangerDSLTests = [
            ("testDangerfileResults", testDangerfileResults),
            ("testFileMapWorksCorrectly", testFileMapWorksCorrectly),
            ("testGithubFixtureDSL", testGithubFixtureDSL),
            ("testItParsesCorrectlyTheDangerDSLWhenThePRIsOnBitBucketServer", testItParsesCorrectlyTheDangerDSLWhenThePRIsOnBitBucketServer),
            ("testItParsesCorrectlyTheDangerDSLWhenThePRIsOnGithubEnterprise", testItParsesCorrectlyTheDangerDSLWhenThePRIsOnGithubEnterprise),
        ]
    }

    extension DangerSwiftLintTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__DangerSwiftLintTests = [
            ("testDeletesReportFile", testDeletesReportFile),
            ("testDoNotExecuteSwiftlintWhenNoFilesToCheck", testDoNotExecuteSwiftlintWhenNoFilesToCheck),
            ("testExecutesQuiet", testExecutesQuiet),
            ("testExecutesSwiftLintWhenLintingAllFiles", testExecutesSwiftLintWhenLintingAllFiles),
            ("testExecutesSwiftLintWhenLintingAllFilesWithDirectoryPassed", testExecutesSwiftLintWhenLintingAllFilesWithDirectoryPassed),
            ("testExecutesSwiftLintWithConfigWhenPassed", testExecutesSwiftLintWithConfigWhenPassed),
            ("testExecutesSwiftLintWithDirectoryPassed", testExecutesSwiftLintWithDirectoryPassed),
            ("testExecutesTheShell", testExecutesTheShell),
            ("testExecutesTheShellWithCustomSwiftLintPath", testExecutesTheShellWithCustomSwiftLintPath),
            ("testExecutesVerboseIfNotQuiet", testExecutesVerboseIfNotQuiet),
            ("testExecuteSwiftLintInInlineMode", testExecuteSwiftLintInInlineMode),
            ("testExecuteSwiftWithStructAndInlineMode", testExecuteSwiftWithStructAndInlineMode),
            ("testFiltersOnSwiftFiles", testFiltersOnSwiftFiles),
            ("testMarkdownReporting", testMarkdownReporting),
            ("testMarkdownReportingInStrictMode", testMarkdownReportingInStrictMode),
            ("testMarkdownReportingWithoutFilePath", testMarkdownReportingWithoutFilePath),
            ("testPrintsNoMarkdownIfNoViolations", testPrintsNoMarkdownIfNoViolations),
            ("testQuotesPathArguments", testQuotesPathArguments),
            ("testSendsOuputFileToTheExecutorWhenLintingAllTheFiles", testSendsOuputFileToTheExecutorWhenLintingAllTheFiles),
            ("testSendsOuputFileToTheExecutorWhenLintingModifiedFiles", testSendsOuputFileToTheExecutorWhenLintingModifiedFiles),
            ("testSpecificFilesLintStyle", testSpecificFilesLintStyle),
            ("testSpecificFilesSwiftOnlyFilter", testSpecificFilesSwiftOnlyFilter),
            ("testViolations", testViolations),
        ]
    }

    extension DangerUtilsLineSearchTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__DangerUtilsLineSearchTests = [
            ("testItReturnsAnEmptyArrayIfNoResultsAreFound", testItReturnsAnEmptyArrayIfNoResultsAreFound),
            ("testItReturnsTheCorrectResultsIfTheSearchedStringIsPresent", testItReturnsTheCorrectResultsIfTheSearchedStringIsPresent),
        ]
    }

    extension DangerUtilsTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__DangerUtilsTests = [
            ("testAwaitsFunctionResult", testAwaitsFunctionResult),
            ("testFileDiffWhenDiffIsValid", testFileDiffWhenDiffIsValid),
            ("testLinesForStringReturnsTheCorrectResult", testLinesForStringReturnsTheCorrectResult),
        ]
    }

    extension DateFormatterExtensionTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__DateFormatterExtensionTests = [
            ("test_DateFormatter_dateFromString", test_DateFormatter_dateFromString),
            ("test_DateFormatter_nilFromInvalidString", test_DateFormatter_nilFromInvalidString),
        ]
    }

    extension DateFormatterHandlerTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__DateFormatterHandlerTests = [
            ("testOnlyDateParseSuccess", testOnlyDateParseSuccess),
            ("testRegularParseSuccess", testRegularParseSuccess),
            ("testUnexpectedDateThrows", testUnexpectedDateThrows),
        ]
    }

    extension DefaultDateFormatterTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__DefaultDateFormatterTests = [
            ("testParsesDateWithMilliseconds", testParsesDateWithMilliseconds),
            ("testParsesDateWithoutMilliseconds", testParsesDateWithoutMilliseconds),
        ]
    }

    extension FileTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__FileTests = [
            ("test_fileType_forHFile", test_fileType_forHFile),
            ("test_fileType_forJSON", test_fileType_forJSON),
            ("test_fileType_forM", test_fileType_forM),
            ("test_fileType_forMarkdown", test_fileType_forMarkdown),
            ("test_fileType_forMM", test_fileType_forMM),
            ("test_fileType_forPbxproj", test_fileType_forPbxproj),
            ("test_fileType_forPlist", test_fileType_forPlist),
            ("test_fileType_forStoryboard", test_fileType_forStoryboard),
            ("test_fileType_forSwift", test_fileType_forSwift),
            ("test_fileType_forXCScheme", test_fileType_forXCScheme),
            ("test_fileType_forYAML", test_fileType_forYAML),
            ("test_fileType_forYML", test_fileType_forYML),
            ("test_fileType_withMultipleDots", test_fileType_withMultipleDots),
        ]
    }

    extension FileTypeTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__FileTypeTests = [
            ("test_extension_matchesRawValue", test_extension_matchesRawValue),
        ]
    }

    extension GitDiffTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__GitDiffTests = [
            ("testChangeTypeForCreated", testChangeTypeForCreated),
            ("testChangeTypeForDeleted", testChangeTypeForDeleted),
            ("testChangeTypeForModified", testChangeTypeForModified),
            ("testChangeTypeForRenamed", testChangeTypeForRenamed),
            ("testParsesDiff", testParsesDiff),
        ]
    }

    extension GitHubTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__GitHubTests = [
            ("test_GitHubBot_decode", test_GitHubBot_decode),
            ("test_GitHubCommit_decode", test_GitHubCommit_decode),
            ("test_GitHubCommit_decodesJSONWithEmptyAuthor", test_GitHubCommit_decodesJSONWithEmptyAuthor),
            ("test_GitHubIssue_decode", test_GitHubIssue_decode),
            ("test_GitHubIssue_emptyBody_decode", test_GitHubIssue_emptyBody_decode),
            ("test_GitHubIssueLabel_decode", test_GitHubIssueLabel_decode),
            ("test_GitHubMergeRef_decode", test_GitHubMergeRef_decode),
            ("test_GitHubMilestone_decodeWithAllParameters", test_GitHubMilestone_decodeWithAllParameters),
            ("test_GitHubMilestone_decodeWithoutDescription", test_GitHubMilestone_decodeWithoutDescription),
            ("test_GitHubMilestone_decodeWithSomeParameters", test_GitHubMilestone_decodeWithSomeParameters),
            ("test_GitHubPR_decode", test_GitHubPR_decode),
            ("test_GitHubRepo_decode", test_GitHubRepo_decode),
            ("test_GitHubReview_decode", test_GitHubReview_decode),
            ("test_GitHubTeam_decode", test_GitHubTeam_decode),
            ("test_GitHubUser_decode", test_GitHubUser_decode),
        ]
    }

    extension GitLabMilestoneTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__GitLabMilestoneTests = [
            ("testParseGroupMilestone", testParseGroupMilestone),
            ("testParseMilestoneFailure", testParseMilestoneFailure),
            ("testParseProjectMilestone", testParseProjectMilestone),
        ]
    }

    extension GitLabTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__GitLabTests = [
            ("testMilestoneWithoutDueDate", testMilestoneWithoutDueDate),
            ("testParsesCorrectlyMetadata", testParsesCorrectlyMetadata),
            ("testParsesMergeRequest", testParsesMergeRequest),
        ]
    }

    extension GitTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__GitTests = [
            ("test", test),
        ]
    }

    extension NSRegularExpressionExtensionsTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__NSRegularExpressionExtensionsTests = [
            ("test_firstMatchingString_failingRegex", test_firstMatchingString_failingRegex),
            ("test_firstMatchingString_passingRegex", test_firstMatchingString_passingRegex),
        ]
    }

    extension OnlyDateDateFormatterTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__OnlyDateDateFormatterTests = [
            ("testParsesDate", testParsesDate),
        ]
    }

    extension SwiftlintDefaultPathTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__SwiftlintDefaultPathTests = [
            ("testItReturnsTheSPMCommandIfThePackageContainsTheSwiftlintDependency", testItReturnsTheSPMCommandIfThePackageContainsTheSwiftlintDependency),
            ("testItReturnsTheSwiftlintCLICommandIfThePackageContainsTheSwiftlintDependency", testItReturnsTheSwiftlintCLICommandIfThePackageContainsTheSwiftlintDependency),
        ]
    }

    extension SwiftlintReportDeleterTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__SwiftlintReportDeleterTests = [
            ("testCallsRemoveItemOnFileManager", testCallsRemoveItemOnFileManager),
        ]
    }

    extension ViolationTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__ViolationTests = [
            ("testDecoding", testDecoding),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        [
            testCase(BitBucketCloudTests.__allTests__BitBucketCloudTests),
            testCase(BitBucketServerTests.__allTests__BitBucketServerTests),
            testCase(DangerDSLTests.__allTests__DangerDSLTests),
            testCase(DangerSwiftLintTests.__allTests__DangerSwiftLintTests),
            testCase(DangerUtilsLineSearchTests.__allTests__DangerUtilsLineSearchTests),
            testCase(DangerUtilsTests.__allTests__DangerUtilsTests),
            testCase(DateFormatterExtensionTests.__allTests__DateFormatterExtensionTests),
            testCase(DateFormatterHandlerTests.__allTests__DateFormatterHandlerTests),
            testCase(DefaultDateFormatterTests.__allTests__DefaultDateFormatterTests),
            testCase(FileTests.__allTests__FileTests),
            testCase(FileTypeTests.__allTests__FileTypeTests),
            testCase(GitDiffTests.__allTests__GitDiffTests),
            testCase(GitHubTests.__allTests__GitHubTests),
            testCase(GitLabMilestoneTests.__allTests__GitLabMilestoneTests),
            testCase(GitLabTests.__allTests__GitLabTests),
            testCase(GitTests.__allTests__GitTests),
            testCase(NSRegularExpressionExtensionsTests.__allTests__NSRegularExpressionExtensionsTests),
            testCase(OnlyDateDateFormatterTests.__allTests__OnlyDateDateFormatterTests),
            testCase(SwiftlintDefaultPathTests.__allTests__SwiftlintDefaultPathTests),
            testCase(SwiftlintReportDeleterTests.__allTests__SwiftlintReportDeleterTests),
            testCase(ViolationTests.__allTests__ViolationTests),
        ]
    }
#endif
