
public let GitHubMilestoneJSONWithSomeParameters = """

{"url":"https://api.github.com/repos/GitHawkApp/GitHawk/milestones/11","html_url":"https://github.com/GitHawkApp/GitHawk/milestone/11","labels_url":"https://api.github.com/repos/GitHawkApp/GitHawk/milestones/11/labels","id":3050458,"number":11,"title":"1.19.0","creator":{"login":"rnystrom","id":739696,"avatar_url":"https://avatars2.githubusercontent.com/u/739696?v=4","gravatar_id":"","url":"https://api.github.com/users/rnystrom","html_url":"https://github.com/rnystrom","followers_url":"https://api.github.com/users/rnystrom/followers","following_url":"https://api.github.com/users/rnystrom/following{/other_user}","gists_url":"https://api.github.com/users/rnystrom/gists{/gist_id}","starred_url":"https://api.github.com/users/rnystrom/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rnystrom/subscriptions","organizations_url":"https://api.github.com/users/rnystrom/orgs","repos_url":"https://api.github.com/users/rnystrom/repos","events_url":"https://api.github.com/users/rnystrom/events{/privacy}","received_events_url":"https://api.github.com/users/rnystrom/received_events","type":"User","site_admin":false},"open_issues":0,"closed_issues":2,"state":"open","created_at":"2018-01-20T16:29:28Z","updated_at":"2018-02-27T06:23:58Z","due_on":null,"closed_at":null}

"""

public let GitHubMilestoneJSONWithAllParameters = """

{"url":"https://api.github.com/repos/GitHawkApp/GitHawk/milestones/11","html_url":"https://github.com/GitHawkApp/GitHawk/milestone/11","labels_url":"https://api.github.com/repos/GitHawkApp/GitHawk/milestones/11/labels","id":3050458,"number":11,"title":"1.19.0","description":"kdsjfls","creator":{"login":"rnystrom","id":739696,"avatar_url":"https://avatars2.githubusercontent.com/u/739696?v=4","gravatar_id":"","url":"https://api.github.com/users/rnystrom","html_url":"https://github.com/rnystrom","followers_url":"https://api.github.com/users/rnystrom/followers","following_url":"https://api.github.com/users/rnystrom/following{/other_user}","gists_url":"https://api.github.com/users/rnystrom/gists{/gist_id}","starred_url":"https://api.github.com/users/rnystrom/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rnystrom/subscriptions","organizations_url":"https://api.github.com/users/rnystrom/orgs","repos_url":"https://api.github.com/users/rnystrom/repos","events_url":"https://api.github.com/users/rnystrom/events{/privacy}","received_events_url":"https://api.github.com/users/rnystrom/received_events","type":"User","site_admin":false},"open_issues":0,"closed_issues":2,"state":"open","created_at":"2018-01-20T16:29:28Z","updated_at":"2018-02-27T06:23:58Z","due_on":"2018-03-27T07:10:01Z","closed_at":"2018-03-20T09:46:21Z"}

"""
