public let GitHubIssueJSON = """

{
"url": "https://api.github.com/repos/davdroman/Badonde/issues/96",
"repository_url": "https://api.github.com/repos/davdroman/Badonde",
"labels_url": "https://api.github.com/repos/davdroman/Badonde/issues/96/labels{/name}",
"comments_url": "https://api.github.com/repos/davdroman/Badonde/issues/96/comments",
"events_url": "https://api.github.com/repos/davdroman/Badonde/issues/96/events",
"html_url": "https://github.com/davdroman/Badonde/pull/96",
"id": 447357592,
"node_id": "MDExOlB1bGxSZXF1ZXN0MjgxMzcxNTI2",
"number": 96,
"title": "Some commit that modifies a Swift file",
"user": {
"login": "davdroman",
"id": 2538074,
"node_id": "MDQ6VXNlcjI1MzgwNzQ=",
"avatar_url": "https://avatars2.githubusercontent.com/u/2538074?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/davdroman",
"html_url": "https://github.com/davdroman",
"followers_url": "https://api.github.com/users/davdroman/followers",
"following_url": "https://api.github.com/users/davdroman/following{/other_user}",
"gists_url": "https://api.github.com/users/davdroman/gists{/gist_id}",
"starred_url": "https://api.github.com/users/davdroman/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/davdroman/subscriptions",
"organizations_url": "https://api.github.com/users/davdroman/orgs",
"repos_url": "https://api.github.com/users/davdroman/repos",
"events_url": "https://api.github.com/users/davdroman/events{/privacy}",
"received_events_url": "https://api.github.com/users/davdroman/received_events",
"type": "User",
"site_admin": false
},
"labels": [],
"state": "closed",
"locked": false,
"assignee": null,
"assignees": [],
"milestone": null,
"comments": 1,
"created_at": "2019-05-22T21:46:10Z",
"updated_at": "2019-05-22T23:15:49Z",
"closed_at": "2019-05-22T23:15:46Z",
"author_association": "OWNER",
"pull_request": {
"url": "https://api.github.com/repos/davdroman/Badonde/pulls/96",
"html_url": "https://github.com/davdroman/Badonde/pull/96",
"diff_url": "https://github.com/davdroman/Badonde/pull/96.diff",
"patch_url": "https://github.com/davdroman/Badonde/pull/96.patch"
},
"body": "Some body for the issue",
"closed_by": {
"login": "davdroman",
"id": 2538074,
"node_id": "MDQ6VXNlcjI1MzgwNzQ=",
"avatar_url": "https://avatars2.githubusercontent.com/u/2538074?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/davdroman",
"html_url": "https://github.com/davdroman",
"followers_url": "https://api.github.com/users/davdroman/followers",
"following_url": "https://api.github.com/users/davdroman/following{/other_user}",
"gists_url": "https://api.github.com/users/davdroman/gists{/gist_id}",
"starred_url": "https://api.github.com/users/davdroman/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/davdroman/subscriptions",
"organizations_url": "https://api.github.com/users/davdroman/orgs",
"repos_url": "https://api.github.com/users/davdroman/repos",
"events_url": "https://api.github.com/users/davdroman/events{/privacy}",
"received_events_url": "https://api.github.com/users/davdroman/received_events",
"type": "User",
"site_admin": false
}
}

"""

public let GitHubEmptyBodyIssueJSON = """

{
"url": "https://api.github.com/repos/davdroman/Badonde/issues/96",
"repository_url": "https://api.github.com/repos/davdroman/Badonde",
"labels_url": "https://api.github.com/repos/davdroman/Badonde/issues/96/labels{/name}",
"comments_url": "https://api.github.com/repos/davdroman/Badonde/issues/96/comments",
"events_url": "https://api.github.com/repos/davdroman/Badonde/issues/96/events",
"html_url": "https://github.com/davdroman/Badonde/pull/96",
"id": 447357592,
"node_id": "MDExOlB1bGxSZXF1ZXN0MjgxMzcxNTI2",
"number": 96,
"title": "Some commit that modifies a Swift file",
"user": {
"login": "davdroman",
"id": 2538074,
"node_id": "MDQ6VXNlcjI1MzgwNzQ=",
"avatar_url": "https://avatars2.githubusercontent.com/u/2538074?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/davdroman",
"html_url": "https://github.com/davdroman",
"followers_url": "https://api.github.com/users/davdroman/followers",
"following_url": "https://api.github.com/users/davdroman/following{/other_user}",
"gists_url": "https://api.github.com/users/davdroman/gists{/gist_id}",
"starred_url": "https://api.github.com/users/davdroman/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/davdroman/subscriptions",
"organizations_url": "https://api.github.com/users/davdroman/orgs",
"repos_url": "https://api.github.com/users/davdroman/repos",
"events_url": "https://api.github.com/users/davdroman/events{/privacy}",
"received_events_url": "https://api.github.com/users/davdroman/received_events",
"type": "User",
"site_admin": false
},
"labels": [],
"state": "closed",
"locked": false,
"assignee": null,
"assignees": [],
"milestone": null,
"comments": 1,
"created_at": "2019-05-22T21:46:10Z",
"updated_at": "2019-05-22T23:15:49Z",
"closed_at": "2019-05-22T23:15:46Z",
"author_association": "OWNER",
"pull_request": {
"url": "https://api.github.com/repos/davdroman/Badonde/pulls/96",
"html_url": "https://github.com/davdroman/Badonde/pull/96",
"diff_url": "https://github.com/davdroman/Badonde/pull/96.diff",
"patch_url": "https://github.com/davdroman/Badonde/pull/96.patch"
},
"body": null,
"closed_by": {
"login": "davdroman",
"id": 2538074,
"node_id": "MDQ6VXNlcjI1MzgwNzQ=",
"avatar_url": "https://avatars2.githubusercontent.com/u/2538074?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/davdroman",
"html_url": "https://github.com/davdroman",
"followers_url": "https://api.github.com/users/davdroman/followers",
"following_url": "https://api.github.com/users/davdroman/following{/other_user}",
"gists_url": "https://api.github.com/users/davdroman/gists{/gist_id}",
"starred_url": "https://api.github.com/users/davdroman/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/davdroman/subscriptions",
"organizations_url": "https://api.github.com/users/davdroman/orgs",
"repos_url": "https://api.github.com/users/davdroman/repos",
"events_url": "https://api.github.com/users/davdroman/events{/privacy}",
"received_events_url": "https://api.github.com/users/davdroman/received_events",
"type": "User",
"site_admin": false
}
}

"""
